global:
  scrape_interval:     1s
  evaluation_interval: 5s
# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yaml
scrape_configs:
- job_name: products
  honor_labels: true
  static_configs:
  - targets: ['prometheus.devops:5000']