name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
  AWS_ACCESS_KEY_ID: mock-access
  AWS_SECRET_ACCESS_KEY: mock-secret
  AWS_DEFAULT_REGION: eu-west-3
  AWS_DEFAULT_OUTPUT: json
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: cd api && npm install
      - name: Run tests
        run: cd api && npm test
  build_and_push:
    name: Push Docker image to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: "sindajeddey"
          password: "Sandouda12"
          #          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      #      - name: Extract metadata (tags, labels) for Docker
      #        id: meta
      #        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #        with:
      #          images: segflow/exampleimage
      #          tags: |
      #            type=sha

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./api/
          push: true
          tags: sindajeddey/backend-devops:dev
      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./prometheus/
          push: true
          tags: sindajeddey/prometheus:dev