name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-3
  AWS_DEFAULT_OUTPUT: json
jobs:
  test_backend_application:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: cd api && npm install
      - name: Run tests
        run: cd api && npm test
  build_and_push_docker:
    name: Push Docker image to Docker Hub
    environment: Dev
    needs: test_backend_application
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./api/
          push: true
          tags: sindajeddey/backend-devops:dev
      - name: Build and push Prometheus Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./prometheus/
          push: true
          tags: sindajeddey/prometheus:dev
  deploy:
    name: Build and Copy FrontEnd to S3
    environment: Dev
    env:
      CI: false
    needs: build_and_push_docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        run: cd infra && terraform init
      - name: Terraform Apply
        run: cd infra && terraform apply -auto-approve
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Deploy FrontEND
        run: cd client && make deploy